from . import sale_order
from . import account_move
from . import account_move_line
from . import sale_order_line
from . import product_category
from . import product_template
from . import res_partner
from . import account_payment_register
from . import account_payment
